[SPC-kernel]
partof = "REQ-1-kernel"
text = '''
Redox's kernel shall be a microkernel. Microkernels stand out in their design
by providing minimal abstractions in kernel-space. Microkernels have an
emphasis on user space, unlike Monolithic kernels which have an emphasis on
kernel space.

The basic philosophy of microkernels is that any component which can run in
user space should run in user space. Kernel-space should only be utilized for
the most essential components (e.g., system calls, process separation, resource
management, IPC, thread management, etc).

The kernel's main task should be to act as a medium for communication and
segregation of processes. The kernel should provide minimal abstraction over
the hardware (that is, drivers which can and should run in user mode).

![micro vs macro kernels][1]

[1]: https://upload.wikimedia.org/wikipedia/commons/6/67/OS-structure.svg

The design of the kernel follows a few basic principles:
- use the rust type system to create state abstractions (not custom state
  machines)
- avoid `unsafe` blocks, and when used should use `assert!` for any
  assumptions in unsafe blocks. Prefer kernel panics over security
  vulnerabilities. 
- in general, use lots of `debug_assert!` statements for any assumptions
  that are being made.
'''


